- name: Install Jenkins and Ansible
  hosts: prod_servers
  become: yes

  tasks:
  - name: Epel Installation
    shell: amazon-linux-extras enable ansible2

  - name: Ansible Installation
    yum: name=ansible state=latest

  - name: Prepareing for Jenkins Installation
    get_url: url=https://pkg.jenkins.io/redhat/jenkins.repo dest=/etc/yum.repos.d/jenkins.repo

  - name: Another Preparing
    shell: rpm --import https://pkg.jenkins.io/redhat/jenkins.io.key

#    shell: wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat/jenkins.repo && rpm --import https://pkg.jenkins.io/redhat/jenkins.io.key

  - name: Upgrade repo
    yum: name=* state=latest

  - name: Java Installation
    shell: amazon-linux-extras install -y java-openjdk11

#    yum: name=java-11-openjdk state=present

  - name: Jenkins Installation
    yum: name=jenkins state=latest

  - name: starting Jenkins
    shell: systemctl enable jenkins && systemctl start jenkins

  - name: Copy key
    copy: src=/home/vladimir/client_key-ca-central-1.pem dest=/home/ec2-user/client_key-ca-central-1.pem
