- name: Install Jenkins and Ansible
  hosts: all
  become: yes

  tasks:
          #==========Configure for all Servers==========#
  - name: Java Installation
    shell: amazon-linux-extras install -y java-openjdk11

  - name: Installing Git
    yum: name=git state=latest

  - block: #==========Master Configuring==========#
      - name: Prepareing for Jenkins Installation
        get_url: url=https://pkg.jenkins.io/redhat/jenkins.repo dest=/etc/yum.repos.d/jenkins.repo

      - name: Another Preparing
        shell: rpm --import https://pkg.jenkins.io/redhat/jenkins.io.key

      - name: Upgrade repo
        yum: name=* state=latest

      - name: Jenkins Installation
        yum: name=jenkins state=latest

      - name: starting Jenkins
        shell: systemctl enable jenkins && systemctl start jenkins

      - name: create .ssh directory
        file:
          path: /var/lib/jenkins/.ssh
          state: directory
        become: true
        become_user: jenkins

      - name: Copy key for slave server
        copy: src={{ home_path }}/.ssh/{{ slave_key }} dest=/var/lib/jenkins/.ssh/slave-key.pem mode=0600
        become: true
        become_user: jenkins

      - name: create known_hosts file
        shell: echo "github.com,140.82.114.4 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg= " > /var/lib/jenkins/.ssh/known_hosts
        become: true
        become_user: jenkins

    delegate_to: "{{ groups['master_server'][0] }}"

  - block: #==========Wagtail-Slaves Configuring==========#
      - name: Epel Installation
        shell: amazon-linux-extras enable ansible2

      - name: Ansible Installation
        yum: name=ansible state=latest

      - name: Installing config-manager
        yum: name=yum-utils state=latest

      - name: Adding repo
        shell: yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo

      - name: Installing Terraform
        yum: name=terraform state=latest

      - name: create known_hosts file
        shell: echo "github.com,140.82.114.4 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg= " > /home/ec2-user/.ssh/known_hosts
        become: true
        become_user: ec2-user

      - name: Copy private key for git
        copy: src={{ home_path }}/.ssh/id_rsa dest=/home/ec2-user/.ssh/id_rsa mode=0600
        become: true
        become_user: ec2-user

      - name: Copy key for remote server
        copy: src={{ home_path }}/.ssh/{{ wagtail_key }} dest=/home/ec2-user/.ssh/client_key.pem mode=0600
        become: true
        become_user: ec2-user

      - name: copy tfvars file in server
        copy: src=prod.tfvars dest=~/prod.tfvars
        become: true
        become_user: ec2-user

    delegate_to: "{{ groups['slave_server'][0] }}"

  - block: #==========Kubernetes-Slave Configuration==========#

      - name: install eksctl
        shell: curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp

      - name: move eksctl
        shell: sudo mv /tmp/eksctl /usr/local/bin
        ignore_errors: True

      - name: install kubectl
        shell: curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.24.7/2022-10-31/bin/linux/amd64/kubectl

      - name: chmod for kubectl
        shell: chmod +x /home/ec2-user/kubectl

      - name: create known_hosts file
        shell: echo "github.com,140.82.114.4 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg= " > /home/ec2-user/.ssh/known_hosts
        become: true
        become_user: ec2-user

      - name: Copy private key for git
        copy: src={{ home_path }}/.ssh/id_rsa dest=/home/ec2-user/.ssh/id_rsa mode=0600
        become: true
        become_user: ec2-user
    delegate_to: "{{ groups['slave_server'][1] }}"
